create or replace view RAW_PRD_SAP.EP1.VW_LISTA_PEDIDOS_COMPRA_MATERIAL(
	DOCUMENTO_COMPRAS,
	POSICION,
	INDICADOR_BORRADO,
	PROVEEDOR_CENTRO_SUMINISTRO,
	MATERIAL,
	MATERIAL_TEXTO_BREVE,
	GRUPO_COMPRAS,
	SOLICITUD_PEDIDO,
	SOLICITUD_PEDIDO_POSICION,
	GRUPO_ARTICULO,
	CENTRO,
	FECHA_DOCUMENTO,
	UNIDAD_MEDIDA_PEDIDO,
	CANTIDAD,
	POR_ENTREGAR_CANTIDAD,
	MONEDA,
	PRECIO_NETO,
	VALOR_NETO
) as
(
WITH ME2M AS
(
    SELECT
        DOCUMENTO_COMPRAS,
        POSICION,
        PROVEEDOR_CENTRO_SUMINISTRO,
        GRUPO_COMPRAS,
        POR_ENTRG AS POR_ENTREGAR_CANTIDAD,
        MONEDA
FROM RAW_PRD_SAP.EP1.ME2M
ORDER BY DOCUMENTO_COMPRAS, POSICION
),
EKPO AS
(
    SELECT
        EBELN AS DOCUMENTO_COMPRAS,
        CAST(EBELP AS INTEGER) AS DOCUMENTO_COMPRAS_POSICION,
        LOEKZ AS INDICADOR_BORRADO,
        MATNR AS MATERIAL,
        TXZ01 AS MATERIAL_TEXTO_BREVE,
        BANFN AS SOLICITUD_PEDIDO,
        BNFPO AS SOLICITUD_PEDIDO_POSICION,
        MATKL AS GRUPO_ARTICULO,
        WERKS AS CENTRO,
        AEDAT AS FECHA_DOCUMENTO,
        MEINS AS UNIDAD_MEDIDA_PEDIDO,
        MENGE AS CANTIDAD,
        NETPR AS PRECIO_NETO,
        NETWR AS VALOR_NETO
    FROM RAW_PRD_SAP.EP1.EKPO
)


SELECT 
    M.DOCUMENTO_COMPRAS,
    M.POSICION,
    E.INDICADOR_BORRADO,
    M.PROVEEDOR_CENTRO_SUMINISTRO,
    E.MATERIAL,
    E.MATERIAL_TEXTO_BREVE,
    M.GRUPO_COMPRAS,
    E.SOLICITUD_PEDIDO,
    E.SOLICITUD_PEDIDO_POSICION,
    E.GRUPO_ARTICULO,
    E.CENTRO,
    E.FECHA_DOCUMENTO,
    E.UNIDAD_MEDIDA_PEDIDO,
    E.CANTIDAD,
    M.POR_ENTREGAR_CANTIDAD,
    M.MONEDA,
    E.PRECIO_NETO,
    E.VALOR_NETO
FROM ME2M M INNER JOIN EKPO E
ON M.DOCUMENTO_COMPRAS = E.DOCUMENTO_COMPRAS
AND M.POSICION = E.DOCUMENTO_COMPRAS_POSICION

);