create or replace view RAW_PRD_SAP.EP1.VW_LISTA_ENTREGAS_SALIENTES(
	ENTREGA,
	CENTRO,
	ALMACEN,
	MATERIAL,
	MATERIAL_DENOMINACION,
	LOTE,
	CANTIDAD_ENTREGA,
	UNIDAD_MEDIDA_VENTA,
	PESO_TOTAL,
	UNIDAD_PESO,
	DESTINATARIO_CLAVE,
	CREADO_POR,
	SOLICITANTE_CLAVE,
	CANTIDAD_REAL_UMA,
	UNIDAD_MEDIDA_BASE,
	FECHA_PREFERENTE,
	FECHA_ENTREGAS,
	HORA_ENTREGA,
	DOCUMENTO_MODELO,
	POSICION_MODELO,
	ESTADO_MOVIMIENTO_MERCANCIA
) as
(
SELECT 
    LIKP.VBELN AS ENTREGA,
    LIPS.WERKS AS CENTRO,
    LIPS.LGORT AS ALMACEN,
    LIPS.MATNR AS MATERIAL,
    LIPS.ARKTX AS MATERIAL_DENOMINACION,
    LIPS.CHARG AS LOTE,
    LIPS.LFIMG AS CANTIDAD_ENTREGA,
    LIPS.VRKME AS UNIDAD_MEDIDA_VENTA,
    LIPS.NTGEW AS PESO_TOTAL,
    LIPS.GEWEI AS UNIDAD_PESO,
    LIKP.KUNNR AS DESTINATARIO_CLAVE,
    LIPS.ERNAM AS CREADO_POR,
    LIKP.KUNAG AS SOLICITANTE_CLAVE,
    LIPS.LGMNG AS CANTIDAD_REAL_UMA,
    LIPS.MEINS AS UNIDAD_MEDIDA_BASE,
    LIPS.VFDAT AS FECHA_PREFERENTE,
    LIPS.MBDAT AS FECHA_ENTREGAS,
    LIPS.MBUHR AS HORA_ENTREGA,
    LIPS.VGBEL AS DOCUMENTO_MODELO,
    LIPS.VGPOS AS POSICION_MODELO,    
    VBUK.WBSTK AS ESTADO_MOVIMIENTO_MERCANCIA
FROM RAW_PRD_SAP.EP1.LIKP INNER JOIN RAW_PRD_SAP.EP1.VBUK
ON LIKP.VBELN = VBUK.VBELN INNER JOIN RAW_PRD_SAP.EP1.LIPS_CARGA AS LIPS
ON LIKP.VBELN = LIPS.VBELN
);